# Data Mining Final Project

# Naive Bayes Algorithm

# Importing Libraries 

In [159]:
import pandas as pd
import numpy as np
from sklearn import neighbors, preprocessing, model_selection
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.naive_bayes import GaussianNB

# Importing the Dataset from the path

In [160]:
Vehicle = pd.read_csv(r'C:\Akhil\NJIT Courses\Data Mining\NagaAkhil_Desabattina_Finaltermproj\vehicle_stolen_dataset.csv')

In [161]:
Vehicle

number_plate   brand  color   time stoled
0          N001     BMW  black  night    yes
1          N002    Audi  black  night     no
2          N003  NISSAN  black  night    yes
3          N004    VEGA    red    day    yes
4          N005     BMW   blue    day     no
5          N006    Audi  black    day    yes
6          N007    VEGA    red  night     no
7          N008    Audi   blue    day    yes
8          N009    VEGA  black    day    yes
9          N010  NISSAN   blue    day     no
10         N011     BMW  black  night    yes
11         N012  NISSAN    red    day     no
12         N013    VEGA  black  night    yes
13         N014     BMW    red    day     no
14         N015    Audi  black    day    yes
15         N016    Audi   blue  night    yes
16         N017    Audi    red    day     no
17         N018  NISSAN  black    day    yes
18         N019     BMW   blue    day    yes
19         N020     BMW    red  night    yes

# Checking for Null Values

In [162]:
Vehicle.isna().mean()

number_plate    0.0
brand           0.0
color           0.0
time            0.0
stoled          0.0
dtype: float64

In [163]:
Vehicle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   number_plate  20 non-null     object
 1   brand         20 non-null     object
 2   color         20 non-null     object
 3   time          20 non-null     object
 4   stoled        20 non-null     object
dtypes: object(5)
memory usage: 928.0+ bytes


# Dataframe

In [164]:
Vehicle_df = Vehicle

# Identifying Columns

In [165]:
label_cols = ['number_plate', 'brand', 'time', 'color']

# Identifying Target Column

In [166]:
TARGET = 'stoled'

# Label Encoding the data

In [167]:
from sklearn.preprocessing import LabelEncoder

In [168]:
def label_encoder(c):
    label_enc = LabelEncoder()
    return label_enc.fit_transform(c)

In [169]:
label_encoded_df = Vehicle_df[label_cols].apply(label_encoder)

In [170]:
target_df = Vehicle_df[TARGET]

# Concatenating the Label Encoded columns into a single data frame

In [171]:
df = pd.concat([label_encoded_df, target_df], axis=1)

In [172]:
df.head()

number_plate  brand  time  color stoled
0             0      1     1      0    yes
1             1      0     1      0     no
2             2      2     1      0    yes
3             3      3     0      2    yes
4             4      1     0      1     no

In [173]:
df.tail()

number_plate  brand  time  color stoled
15            15      0     1      1    yes
16            16      0     0      2     no
17            17      2     0      0    yes
18            18      1     0      1    yes
19            19      1     1      2    yes

# Assigning X Variable

In [174]:
X = df.drop(['stoled'], axis=1)

In [175]:
X.head()

number_plate  brand  time  color
0             0      1     1      0
1             1      0     1      0
2             2      2     1      0
3             3      3     0      2
4             4      1     0      1

In [176]:
X.shape

(20, 4)

# Assigning Y Variable

In [177]:
y = df['stoled']

In [178]:
y.head()

0    yes
1     no
2    yes
3    yes
4     no
Name: stoled, dtype: object

# Splitting the Dataset into train and test

In [179]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=168)

# Initiating the Model and fitting the model to the data

In [180]:
from sklearn.naive_bayes import GaussianNB

In [181]:
model = GaussianNB()

In [182]:
model.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [183]:
y_model = model.predict(X_test)

# Accuracy 

In [184]:
from sklearn.metrics import accuracy_score

Accuracy = accuracy_score(y_test, y_model)*100

In [185]:
print(Accuracy)

57.14285714285714


# 10 Cross Validation 

In [186]:
seed = 1
kfolds = model_selection.KFold(n_splits=10, random_state=seed)
kfolds

C:\Users\akhil\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:292: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  warnings.warn(


KFold(n_splits=10, random_state=1, shuffle=False)

In [187]:
model = GaussianNB()
results = model_selection.cross_val_score(model, X_train, y_train, cv=kfolds, scoring='accuracy')
print('Accuracy -val set: %.2f%% (%.2f)' % (results.mean()*100, results.std()))
results

Accuracy -val set: 55.00% (0.47)


array([1. , 0.5, 0. , 0. , 1. , 0. , 0. , 1. , 1. , 1. ])

# Confusion Matrix

In [202]:
from sklearn.metrics import confusion_matrix

In [203]:
cmt = confusion_matrix(y_test, y_model)

In [204]:
print(cmt)

[[0 1]
 [2 4]]


In [207]:
TP = cmt[0][0]
TP

0

In [208]:
FP = cmt[0][1]
FP

1

In [210]:
FN = cmt[1][0]
FN

2

In [212]:
TN = cmt[1][1]
TN

4

In [213]:
# TRUE PSOITIVE
TPR = TP/(TP + TN)
TPR

0.0

In [214]:
# True Negative
TNR = TN/(TN+FP)
TNR

0.8

In [215]:
# FALSE POSITIVE VALUE
FPR = FP/(FP+TN)
FPR

0.2

In [217]:
# FALSE NEGATIVE VALUE
FNR = FN/(TP+FN)
FNR

1.0

In [219]:
# ACCURACY 
ACCU = (TP+TN)/(TP+FP+TN+FN)
ACCU * 100

57.14285714285714

# Random Forest Algorithm

# Importing the Libraries

In [221]:
import pandas as pd
import numpy as np

In [222]:
Vehicle = pd.read_csv(r'C:\Akhil\NJIT Courses\Data Mining\NagaAkhil_Desabattina_Finaltermproj\vehicle_stolen_dataset.csv')

In [223]:
Vehicle

number_plate   brand  color   time stoled
0          N001     BMW  black  night    yes
1          N002    Audi  black  night     no
2          N003  NISSAN  black  night    yes
3          N004    VEGA    red    day    yes
4          N005     BMW   blue    day     no
5          N006    Audi  black    day    yes
6          N007    VEGA    red  night     no
7          N008    Audi   blue    day    yes
8          N009    VEGA  black    day    yes
9          N010  NISSAN   blue    day     no
10         N011     BMW  black  night    yes
11         N012  NISSAN    red    day     no
12         N013    VEGA  black  night    yes
13         N014     BMW    red    day     no
14         N015    Audi  black    day    yes
15         N016    Audi   blue  night    yes
16         N017    Audi    red    day     no
17         N018  NISSAN  black    day    yes
18         N019     BMW   blue    day    yes
19         N020     BMW    red  night    yes

# Checking Null Values

In [224]:
Vehicle.isna().mean()

number_plate    0.0
brand           0.0
color           0.0
time            0.0
stoled          0.0
dtype: float64

In [225]:
Vehicle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   number_plate  20 non-null     object
 1   brand         20 non-null     object
 2   color         20 non-null     object
 3   time          20 non-null     object
 4   stoled        20 non-null     object
dtypes: object(5)
memory usage: 928.0+ bytes


In [226]:
Vehicle_df = Vehicle

# X and Y

In [227]:
X = df.drop(['stoled'], axis=1)

In [228]:
y = df['stoled']

# Splitting the Data into train and test

In [229]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=171)

# Random Forest

In [230]:
from sklearn.ensemble import RandomForestClassifier

In [231]:
rfc = RandomForestClassifier(n_estimators=600)

In [232]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=600,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [233]:
predictions = rfc.predict(X_test)

# 10 Cross Validation

In [234]:
seed = 1
kfold = model_selection.KFold(n_splits=10, random_state=seed)
kfold

C:\Users\akhil\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:292: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  warnings.warn(


KFold(n_splits=10, random_state=1, shuffle=False)

In [235]:
model = RandomForestClassifier(n_estimators=600)

In [236]:
results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring='accuracy')
print('Accuracy -val set: %.2f%% (%.2f)' % (results.mean()*100, results.std()))
results

Accuracy -val set: 65.00% (0.45)


array([1. , 1. , 0.5, 1. , 1. , 1. , 0. , 0. , 1. , 0. ])

# Confusion Matrix

In [237]:
from sklearn.metrics import confusion_matrix

In [238]:
cmt = confusion_matrix(y_test, predictions)

In [240]:
print(cmt)

[[1 2]
 [2 1]]


In [241]:
TP = cmt[0][0]
TP

1

In [242]:
FP = cmt[0][1]
FP

2

In [243]:
FN = cmt[1][0]
FN

2

In [244]:
TN = cmt[1][1]
TN

1

In [245]:
# TRUE PSOITIVE
TPR = TP/(TP + TN)
TPR

0.5

In [246]:
# True Negative
TNR = TN/(TN+FP)
TNR

0.3333333333333333

In [247]:
# FALSE POSITIVE VALUE
FPR = FP/(FP+TN)
FPR

0.6666666666666666

In [248]:
# FALSE NEGATIVE VALUE
FNR = FN/(TP+FN)
FNR

0.6666666666666666

# LSTM

# Importing Libraries

In [101]:
import tensorflow as tf
from keras.preprocessing import sequence 
from keras.models import Sequential 
from keras.layers import Dense, Dropout, Embedding, LSTM,Bidirectional 
from keras.datasets import imdb 

# Importing X and Y that we did in the previous 2 algorithms

In [102]:
X.head()

number_plate  brand  time  color
0             0      1     1      0
1             1      0     1      0
2             2      2     1      0
3             3      3     0      2
4             4      1     0      1

In [103]:
y.head()

0    yes
1     no
2    yes
3    yes
4     no
Name: stoled, dtype: object

# Splitting the Data into train and test

In [117]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=141)